upload:
  action: http://192.168.1.166:8081/upload
  path:  D:/apache-tomcat-7.0.70/webapps/upload/vueAdmin
  visit: http://192.168.1.166:9080/upload/vueAdmin
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vue_admin_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.1.254
    port: 6379
    timeout: 10000
    pool:
      max-active: 40
      max-idle: 5
      max-wait: 10000
    password:
mybatis:
  mapper-locations: mapper/**Dao.xml
  configuration:
      map-underscore-to-camel-case: true
